spring.application.name=TechOne_E-Commerce
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=TechOne_Shop;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Multipart Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-swallow-size=-1
server.tomcat.max-parameter-count=10000
server.tomcat.max-part-count=1000
spring.security.oauth2.client.registration.google.client-id=300061867360-fg4tblcnlfok88nnugo1ql1ktob3bj0s.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=awakamayuki@gmail.com
spring.mail.password=oilcjjnzjngrhvaf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
