spring.application.name=TechOne_E-Commerce
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=TechOne_Shop;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Multipart Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-swallow-size=-1
server.tomcat.max-parameter-count=10000
server.tomcat.max-part-count=1000

# File Upload Configuration
app.upload.dir=src/main/resources/static


spring.security.oauth2.client.registration.google.client-id=300061867360-fg4tblcnlfok88nnugo1ql1ktob3bj0s.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# GHN Configuration
ghn.api.url=https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/fee
ghn.api.token=d88f0b5f-057b-11f1-a3d6-dac90fb956b5
ghn.shop.id=199345
ghn.shop.district.id=1544

# Core PayOS credentials
payos.client-id=a34cfe21-df21-4f8d-8a21-a0fb76d68baf
payos.api-key=c27674af-4c0d-4933-9cf4-40d260b1f627
payos.checksum-key=49b6e35e4ee36632b899fa25ff885df17c98c4f3c2aeb5aa8ffe74b60bef5ddc

# Optional: Payout credentials (leave empty if not using payouts)
payos.payout-client-id=a34cfe21-df21-4f8d-8a21-a0fb76d68baf
payos.payout-api-key=c27674af-4c0d-4933-9cf4-40d260b1f627
payos.payout-checksum-key=49b6e35e4ee36632b899fa25ff885df17c98c4f3c2aeb5aa8ffe74b60bef5ddc

# Logging level: DEBUG | INFO | NONE
payos.log-level=NONE

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=awakamayuki@gmail.com
spring.mail.password=fsyfpzclgamvslje
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

