spring.application.name=TechOne_E-Commerce
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TechOne_Shop;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.oauth2.client.registration.google.client-id=300061867360-fg4tblcnlfok88nnugo1ql1ktob3bj0s.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email